#!/bin/sh
# Start/stop mango hypervisor interface
#
# Copyright (c) 2015-2016 ilbers GmbH


PATH=/bin:/usr/bin:/sbin:/usr/sbin

case "$1" in
start)  echo "Starting Mango hypervisor interface"

	# Load Mango API modules
	modprobe mango_core secure_token="bananapi"
	modprobe mango_data_channel nr_devs=1
	modprobe mango_watchdog
	modprobe mango_net_iface

	# Run watchdog daemon
	/usr/bin/wd_daemon

	# Bring up networking
	ifconfig mango0 192.167.20.1 up
	;;
stop)

	# Remove Mango moules
	if [ -n "`lsmod | grep mango_net_iface`" ]; then
		ifconfig mango0 down;
		rmmod mango_net_iface;
	fi
	if [ -n "`lsmod | grep mango_watchdog`" ]; then
		rmmod mango_watchdog;
	fi
	if [ -n "`lsmod | grep mango_data_channel`" ]; then
		rmmod mango_data_channel;
	fi
	if [ -n "`lsmod | grep mango_core`" ]; then
		rmmod mango_core;
	fi
esac

exit 0
